
version: '3.1'

services:

  xldeploy:
    build:
      context: .
    environment:
      ADMIN_PASSWORD: admin
      ACCEPT_EULA: Y
    volumes:
      - ./docker/argos.properties:/opt/xebialabs/xl-deploy-server/config/argos.properties
    ports:
      - 4516:4516
      
  tomcat:
    image: argosnotary/xld-tomcat-target:9.0
    ports:
     - "2022:22"
     - "8082:8080"
     
  testxld:
    image: curlimages/curl
    command: curl --retry-connrefused --retry 10 --retry-delay 0 -u admin:admin "http://xldeploy:4516/deployit/server/state"
    depends_on:
    - xldeploy
