#
# Copyright (C) 2019 - 2020 Rabobank Nederland
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: '3.1'

services:

  xldeploy:
    image: xebialabs/xl-deploy:9.5-debian-slim
    environment:
      ADMIN_PASSWORD: admin
      ACCEPT_EULA: Y
    volumes:
      - ./docker/argos.properties:/opt/xebialabs/xl-deploy-server/config/argos.properties
      - ./build/distributions/xld-argos-plugin-0.0.1-RC4.xldp:/opt/xebialabs/xl-deploy-server/plugins/xld-argos-plugin-0.0.1-RC3-SNAPSHOT.xldp
    ports:
      - 4516:4516
      
  tomcat:
    image: argosnotary/xld-tomcat-target:9.0
    ports:
     - "2022:22"
     - "8082:8080"
