---
kind: pipeline
type: docker
name: xldeploy argos build

platform:
  os: linux
  arch: amd64

steps:
- name: build xlpd
  image: gradle:6.7-jdk8
  commands:
  - gradle license test jacocoTestReport xlPlugin
  volumes:
  - name: mvn_cache
    path: /root/.m2/repository
  when:
    event:
    - pull_request
    
- name: build xlpd secure
  image: gradle:6.7-jdk8
  commands:
  - gradle license test jacocoTestReport xlPlugin javadocJar sourcesJar sonarqube -Dorg.gradle.daemon=false -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_LOGIN -Dsonar.projectKey=xld-argos-plugin -Dsonar.organization=argosnotary
  environment:
    SONAR_LOGIN:
      from_secret: sonar_login
  volumes:
  - name: mvn_cache
    path: /root/.m2/repository
  when:
    event:
    - tag
    - push
    
- name: build images
  image: argosnotary/argos-build:3.6.3-docker
  commands:
  - docker build --tag argosnotary/argos-xldeploy:${DRONE_TAG:-${DRONE_BRANCH//\//_}} --build-arg VERSION=${DRONE_TAG:-${DRONE_BRANCH//\//_}} .
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock
  depends_on:
  - build xlpd
  - build xlpd secure

- name: xldeploy
  image: argosnotary/argos-xldeploy:${DRONE_TAG:-${DRONE_BRANCH//\//_}}
  detach: true
  pull: never
  environment:
    ADMIN_PASSWORD: admin
    ACCEPT_EULA: Y
    JAVA_OPTS: '-Xmx1g'
  depends_on:
  - build images
    
- name: test xld
  image: curlimages/curl
  pull: always
  commands:
  - curl --retry-connrefused --retry 10 --retry-delay 0 -u admin:admin "http://xldeploy:4516/deployit/server/state"
  depends_on:
  - xldeploy

- name: release argos xldeploy image
  image: argosnotary/argos-build:3.6.3-docker
  commands:
  - docker login -u $${DOCKER_USERNAME} -p $${DOCKER_PASSWORD}
  - docker push argosnotary/argos-xldeploy:${DRONE_TAG:-${DRONE_BRANCH//\//_}}
  environment:  
    DOCKER_USERNAME:
      from_secret: docker_login_user  
    DOCKER_PASSWORD:
      from_secret: docker_login_token
  volumes:
  - name: docker_socket
    path: /var/run/docker.sock
  when:
    ref:
      include:
      - "refs/heads/master"
      - "refs/heads/release/*"
    event:
    - push
    - tag
  depends_on:
  - test xld

- name: upload xlpd
  image: gradle:6.7-jdk8
  commands:
  - gradle uploadArchives
  environment:
    ORG_GRADLE_PROJECT_ossrhLoginUser:
      from_secret: ossrh_login_user
    ORG_GRADLE_PROJECT_ossrhLoginPassword:
      from_secret: ossrh_login_password
    ORG_GRADLE_PROJECT_signingPassword:
      from_secret: signing_password
    ORG_GRADLE_PROJECT_signingKey:
        from_secret: signing_key
  volumes:
  - name: mvn_cache
    path: /root/.m2/repository
  depends_on:
  - test xld
  when:
    event:
    - tag
    
volumes:
- name: mvn_cache
  host:
    path: /datadisk/mvn
- name: docker_socket
  host:
    path: /var/run/docker.sock

trigger:
  event:
  - push
  - tag
  - pull_request
...
